"""empty message

Revision ID: c0ee7cb95129
Revises: ab4503794d64
Create Date: 2021-03-28 04:02:23.428218

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "c0ee7cb95129"
down_revision = "ab4503794d64"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "coding_session",
        sa.Column("editor", sa.String(length=20), nullable=True),
    )
    op.add_column(
        "user",
        sa.Column(
            "statistics",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
    )
    op.add_column(
        "user", sa.Column("timezone_offset", sa.Integer(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "timezone_offset")
    op.drop_column("user", "statistics")
    op.drop_column("coding_session", "editor")
    # ### end Alembic commands ###
